root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd"
  bin = "tmp/main.exe"
  include_dir = ["cmd", "views", "css"]
  include_ext = ["go", "html", "css"]
  exclude_dir = ["tmp", "vendor", "node_modules"]

[log]
  time = true

[misc]
  clean_on_exit = true
